export const EVENT_FETCH_REQUEST = 'EVENT_FETCH_REQUEST';
export const EVENT_FETCH_SUCCESS = 'EVENT_FETCH_SUCCESS';
export const EVENT_FETCH_FAILURE = 'EVENT_FETCH_FAILURE';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const CLEAR_FAVORITES = 'CLEAR_FAVORITES';
export const FILTER_EVENTS = 'FILTER_EVENTS';
