export const EVENT_FETCH_REQUEST = 'EVENT_FETCH_REQUEST';
export const EVENT_FETCH_SUCCESS = 'EVENT_FETCH_SUCCESS';
export const EVENT_FETCH_FAILURE = 'EVENT_FETCH_FAILURE';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const CLEAR_FAVORITES = 'CLEAR_FAVORITES';

export const SET_NOTIFY_BEFORE_FAVORITE_START = 'SET_NOTIFY_BEFORE_FAVORITE_START';
export const ADD_SCHEDULED_NOTIFICATION = 'ADD_SCHEDULED_NOTIFICATION';
export const REMOVE_SCHEDULED_NOTIFICATION = 'REMOVE_SCHEDULED_NOTIFICATION';
export const CLEAR_SCHEDULED_NOTIFICATIONS = 'CLEAR_SCHEDULED_NOTIFICATIONS';

export const FILTER_EVENTS = 'FILTER_EVENTS';
